server:
  port: ${GATEWAY_PORT:8080}
  address: ${GATEWAY_ADDRESS:10.117.9.40}

spring:
  codec:
    max-in-memory-size: 100MB
  webflux:
    multipart:
      max-in-memory-size: 100MB
  data:
    redis:
      host: ${REDIS_HOST:10.100.104.24}
      port: ${REDIS_PORT:6400}
      password: ${REDIS_PASSWORD:DHD@ngh222}
  session:
    data:
      redis:
        namespace: "session"
        save-mode: always
    timeout: 30m

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://10.100.104.24:8080/realms/donghee}
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:api-gateway}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:i4BIMYcDHdaFwcj19fFVHOksgg2Rrrqw}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - roles
              - profile
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://10.100.104.24:8080/realms/donghee}
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL:http://10.117.9.40:8086}
              predicates:
                - Path=/api/v1/users/**
            - id: rentals
              uri: ${RENTAL_BACKEND_URL:http://10.117.9.40:8085}
              predicates:
                - Path=/api/v1/**

keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL:http://10.100.104.24:8080}
    realm: ${KEYCLOAK_REALM:donghee}
    client-id: ${KEYCLOAK_CLIENT_ID:api-gateway}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:i4BIMYcDHdaFwcj19fFVHOksgg2Rrrqw}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://10.117.9.40:3000,http://10.117.9.40:4000,http://172.100.74.3:3000}
  client:
    url: ${CLIENT_URL:http://10.117.9.40:3000}

logging:
  level:
    org.springframework.security.web: WARN
    dh.bff: INFO
